### PR TITLE
updating dockerfile for AMD/ARM

### LINKED ISSUE #33: Support ARM arch
Nowadays is common the scenario when users have an ARM machine with Mac M1. KEDA supports ARM64 but this example is build with non ARM64 images, so basically those users cannot test and play with KEDA locally. It'd be nice if we added the needed changes to make this demo runnable on ARM64

### PR DESCRIPTION
**Pull request by jeffhollan**
Resolves #33

### CODE REVIEW

**Comment by JorTurFer** [comment]
If I'm not wrong, we need to update also the readme to use the official docker image for RabbitMQ in helm because bitnami's image doesn't support ARM64. Could you take a look please? 🙏

**Comment by rodrigoechaide** [comment]
@JorTurFer @jeffhollan I was working on the README update. I can upload a PR with those changes.

**Comment by rodrigoechaide** [comment]
This is the [Pull Request](https://github.com/kedacore/sample-go-rabbitmq/pull/35) for the README Update.

**Comment by JorTurFer** [comment]
Thanks!

**Pull request merged**
